name: Summarize TypeScript Files on Push

permissions:
  contents: read
  pull-requests: write

# pushイベント時にトリガー
on:
  push:
    branches:
      - main

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # .tsファイルを全て取得して一つのファイルに結合あ
      - name: Gather TypeScript files
        run: |
          find . -name "*.ts" -not -path "./.git/*" -exec cat {} + > all_ts_code.txt

      # OpenAI APIを使用して、ファイル内容を要約
      - name: Generate summary using OpenAI
        run: |
          curl https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -d '{
            "model": "gpt-3.5-turbo",
            "messages": [
              {"role": "system", "content": "You are an assistant that summarizes TypeScript code."},
              {"role": "user", "content": "Please summarize the following TypeScript code: ```'"$(cat all_ts_code.txt)"'```"}
            ],
            "max_tokens": 1000
          }' > summary.txt

      # 要約結果を表示
      - name: Output summary
        run: cat summary.txt
