name: Code Summary on Push

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get all code
        run: |
          find . -type f \( -name "*.ts" -o -name "*.json" -o -name "*.txt" \) ! -path './.git/*' -not -name 'all_code.txt' -exec cat {} + > all_code.txt

      - name: Generate summary using OpenAI
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          PROMPT: |
            Please summarize the following codebase in a concise manner:
            ```$(cat all_code.txt)```

      - name: Output summary directly
        run: cat all_code.txt  # ファイル内容を再度確認、コンソールに表示
